const companies = [
  { label: 'ABL생명', value: 'LABL' },
  { label: 'Chubb라이프', value: 'LCH' },
  { label: 'DGB생명', value: 'LDGB' },
  { label: 'DB생명', value: 'LDO' },
  { label: '동양생명', value: 'LDY' },
  { label: '한화생명', value: 'LHA' },
  { label: 'ORANGELIFE', value: 'LING' },
  { label: 'KB생명', value: 'LKB' },
  { label: 'KDB생명', value: 'LKDB' },
  { label: '교보생명', value: 'LKY' },
  { label: '라이나생명', value: 'LLI' },
  { label: '미래에셋', value: 'LMI' },
  { label: '메트라이프', value: 'LME' },
  { label: '푸르덴셜생명', value: 'LPU' },
  { label: '삼성생명', value: 'LSA' },
  { label: '신한생명', value: 'LSH' },
  { label: '메리츠화재', value: 'ME' },
  { label: 'MG손해보험', value: 'MG' },
  { label: '농협손해', value: 'NH' },
  { label: '삼성화재', value: 'SA' },
  { label: '한화손해보험', value: 'HA' },
  { label: '흥국화재', value: 'HE' },
  { label: '현대해상화재', value: 'HY' },
  { label: 'KB손해보험', value: 'KB' },
  { label: '롯데손해보험', value: 'LO' },
  { label: 'DB손해보험', value: 'DB' },
  { label: '농협', value: 'LNH' },
  { label: '동부', value: 'LDB' },
  { label: '오렌지', value: 'LORG' },
];
export default companies;
